# https://travis-ci.com/iarp/django-pdf-filler
dist: xenial
language: python

python: "3.6"

env:
  matrix:
   - TOXENV=py27-django111
   - TOXENV=py35-django111
   - TOXENV=py36-django111
   - TOXENV=py35-django20
   - TOXENV=py36-django20
   - TOXENV=py37-django20
   - TOXENV=py35-django21
   - TOXENV=py36-django21
   - TOXENV=py37-django21
   - TOXENV=py35-django22
   - TOXENV=py36-django22
   - TOXENV=py37-django22
   - TOXENV=py36-djangomaster
   - TOXENV=py37-djangomaster
   - TOXENV=docs

matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: TOXENV=py27-django111

    - python: "3.5"
      env: TOXENV=py35-django111
    - python: "3.5"
      env: TOXENV=py35-django20
    - python: "3.5"
      env: TOXENV=py35-django21
    - python: "3.5"
      env: TOXENV=py35-django22

    - python: "3.4"
      env: TOXENV=py34-django111
      dist: trusty
    - python: "3.4"
      env: TOXENV=py34-django20
      dist: trusty

    - python: "3.7"
      env: TOXENV=py37-django111
    - python: "3.7"
      env: TOXENV=py37-django20
    - python: "3.7"
      env: TOXENV=py37-django21
    - python: "3.7"
      env: TOXENV=py37-django22
    - python: "3.7"
      env: TOXENV=py37-djangomaster

  exclude:
    - python: "3.6"
      env: TOXENV=py27-django111
    - python: "3.6"
      env: TOXENV=py35-django111
    - python: "3.6"
      env: TOXENV=py35-django20
    - python: "3.6"
      env: TOXENV=py35-django21
    - python: "3.6"
      env: TOXENV=py35-django22
    - python: "3.6"
      env: TOXENV=py37-django20
    - python: "3.6"
      env: TOXENV=py37-django21
    - python: "3.6"
      env: TOXENV=py37-django22
    - python: "3.6"
      env: TOXENV=py37-djangomaster
  allow_failures:
    - env: TOXENV=py36-djangomaster
    - env: TOXENV=py37-djangomaster

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install --upgrade pip wheel setuptools
  - pip install coveralls tox

script:
  - tox

after_success:
  - coveralls

branches:
 only:
  - master
